### ISSUE TITLE
Expected behavior with HomeAssistant scenes

### ISSUE THREAD

**Issue by rogersmj** [home-assistant/homebridge-homeassistant#88]
I'm a bit confused on how scenes should be handled/seen by HomeKit. The way they're working for me now, I can turn the scene "on" in HomeKit, but then I have to manually tap and turn it off before turning it on again.

My scenes from Home Assistant are seen in HomeKit just fine (as switches). When I turn this "switch" on from the iOS Home app, the scene activates in Home Assistant as expected. However, in the Home app, the switch remains in the *on* state, meaning I have to manually turn it off before I can trigger the scene again.

Is it supposed to behave like this right now? It would seem to make more sense to have any virtual switch that represents a scene flip back to an "off" state in HomeBridge so that it can be triggered again without first being turned off. My first main use case with HomeKit is to make it easy to trigger lighting scenes with Siri from my Apple Watch, and this is complicating things a bit.

**Comment by jamieshaw** [comment]
Agreed. Other Homebridge plugins have switches that toggles back to off once fired, IFTTT is an example of this.
 
For me Homebridge has simply become a way to gain prominent access to Home Assistant through HomeKit. My HomeKit scenes simply turn on the "switch" to activate various HA scenes – from anywhere in iOS or via Siri.

As a result of this setup, "Goodnight Siri" triggers the Goodnight scene which never "turns off". Because the switch is constantly on, the scene reflects this by informing it is also "on".

+1 for turning off Scene switches after triggering.

**Comment by robbiet480** [comment]
Fixed in the upcoming release.

**Comment by tobre6** [comment]
@robbiet480 I tested this out and I think the fix isn't working.

**Comment by robbiet480** [comment]
@tobre6 You tested it by installing directly from GitHub (`npm install -g home-assistant/homebridge-homeassistant`)?

**Comment by tobre6** [comment]
@robbiet480 Yes, I'm running my development branch that is been updated: https://github.com/tobre6/homebridge-homeassistant/blob/development/accessories/switch.js#L57

Switching on the scene on HomeKit don't turn switch nor scene off.

**Comment by jamieshaw** [comment]
@robbiet480 Same issue here. Uninstalled Homebridge-homeassistant and reinstalled directly from the GitHub repo. Restarted Homebridge and the issue persists.

After setting the "Goodnight" scene through Siri last night (only triggers the "Goodnight" switch) and this morning the scene, and switch, are still active.

**Comment by tobre6** [comment]
Please reopen this issue as it is not fixed.

**Comment by heathpitts** [comment]
Would be wonderful to have a fix for this
